// LOCALHOST

### Get all contacts
GET http://localhost:3000/contacts

### Get a single contact by ID
GET http://localhost:3000/contacts/65b5903a4ba2167933005a17

### Create a new contact
POST http://localhost:3000/contacts
content-type: application/json
    
{
    "firstName": "Jar Jar",
    "lastName": "Binks",
    "email": "jar@jar.com",
    "favoriteColor": "Brown",
    "birthday": "05/19/1999"
}

### Update a contact
PUT http://localhost:3000/contacts/65b5a20f109c66867bea6b29
content-type: application/json

{
    "firstName": "Darth",
    "lastName": "Binks",
    "email": "jar@jar.com",
    "favoriteColor": "Red",
    "birthday": "05/19/1999"
}

### Delete a contact
DELETE http://localhost:3000/contacts/65b5a20f109c66867bea6b29


// PRODUCTION Deploy
### Get all contacts
GET https://cse341-0eje.onrender.com/contacts

### Get a single contact by ID
GET https://cse341-0eje.onrender.com/contacts/65b5903a4ba2167933005a17

### Create a new contact
POST https://cse341-0eje.onrender.com/contacts
content-type: application/json
    
{
    "firstName": "Jar Jar",
    "lastName": "Binks",
    "email": "jar@jar.com",
    "favoriteColor": "Brown",
    "birthday": "05/19/1999"
}

### Update a contact
PUT https://cse341-0eje.onrender.com/contacts/65b5a6d1ab3fad3d704419ca
content-type: application/json

{
    "firstName": "Darth",
    "lastName": "Binks",
    "email": "jar@jar.com",
    "favoriteColor": "Red",
    "birthday": "05/19/1999"
}

### Delete a contact
DELETE https://cse341-0eje.onrender.com/contacts/65b5a6d1ab3fad3d704419ca
